### PR TITLE
Add BL to Pip without the autoformatting

### PR DESCRIPTION
**Pull request by lyxal**

### CODE REVIEW

**Review by dloscutoff — CHANGES_REQUESTED** [review]
Please make a few small changes:

- In the error case, `return nil` after showing the warning (otherwise `None` is returned, which causes problems)
- Add a comma at the end of the list entry in `operators.py` (having a comma at the end of every entry, including the last one, makes it easier to copy-paste entries)
- Update the `COMMIT_DATE` in `version.py`

After that, I will check this out locally so I can test it and then probably merge it into a new 1.2 branch. 😃

**Comment by JoaoFelipe3** [comment]
TBH, we can just use `#TBx`.

**Comment by Lyxal** [comment]
> Please make a few small changes:
> 
>     * In the error case, `return nil` after showing the warning (otherwise `None` is returned, which causes problems)
> 
>     * Add a comma at the end of the list entry in `operators.py` (having a comma at the end of every entry, including the last one, makes it easier to copy-paste entries)
> 
>     * Update the `COMMIT_DATE` in `version.py`
> 
> 
> After that, I will check this out locally so I can test it and then probably merge it into a new 1.2 branch. 😃

It may be a few months late, but I finally did it!

**Review by dloscutoff — APPROVED** [review]

**Comment by dloscutoff** [comment]
> It may be a few months late, but I finally did it!

... Same here. ;^P

Funny story, though: The code... uh... didn't work. It needed to return a Scalar, but it was returning a Python int. I completely failed to notice this, despite looking at it multiple times. (Turns out there's no substitute for actually running the code.)

Then, when I asked in TNB what bit-length should do with negative numbers, Bubbler informed me that Python has a built-in. So I used that instead of your implementation.

In the end, despite those and other hiccups, Pip now has a `BL` operator. So thanks!

**Pull request merged**
